# Generated by Django 4.2.13 on 2024-05-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ankete",
            fields=[
                ("ankete_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="ClosedInfo",
            fields=[
                ("ankete_id", models.IntegerField(primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "invitation_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("from_id", models.IntegerField()),
                ("to_id", models.IntegerField()),
                ("description", models.TextField()),
                ("photo", models.BinaryField(blank=True, null=True)),
                ("video", models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvitationToAnkete",
            fields=[
                (
                    "invitation_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("ankete_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Keywords",
            fields=[
                ("ankete_id", models.IntegerField(primary_key=True, serialize=False)),
                ("hobby", models.CharField(max_length=100)),
                ("alcohol", models.CharField(max_length=100)),
                ("smoking", models.CharField(max_length=100)),
                ("sport", models.CharField(max_length=100)),
                ("zodiac_sign", models.CharField(max_length=20)),
                ("height", models.IntegerField()),
                ("age", models.IntegerField()),
                ("why_here", models.TextField()),
                ("marital_status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="OpenInfo",
            fields=[
                ("ankete_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=200)),
                ("sex", models.CharField(max_length=10)),
                ("profile_picture", models.BinaryField(blank=True, null=True)),
                ("age", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PasswordRestoration",
            fields=[
                ("ankete_id", models.IntegerField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=10)),
            ],
        ),
    ]
