# Generated by Django 4.2.13 on 2024-05-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_work_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keywords",
            name="age",
        ),
        migrations.RemoveField(
            model_name="openinfo",
            name="profile_picture",
        ),
    ]
