# Generated by Django 4.2.13 on 2024-05-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_work_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ankete",
            name="login",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ankete",
            name="password",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
