# Generated by Django 4.2.13 on 2024-05-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_work_app", "0002_ankete_login_ankete_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ankete",
            name="login",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="ankete",
            name="password",
            field=models.TextField(default=""),
        ),
    ]
