# Generated by Django 4.2.13 on 2024-05-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_work_app", "0002_remove_keywords_age_remove_openinfo_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePicture",
            fields=[
                ("ankete_id", models.IntegerField(primary_key=True, serialize=False)),
                ("profile_picture", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
